ARG BASE_IMAGE="ubuntu:22.04"
FROM $BASE_IMAGE as base_image

ARG CONFIG_DIR_SRC="/dockerconfig"
ARG DEBIAN_FRONTEND noninteractive

RUN apt update && \
    apt install -y \
    iptables \
    python3 \
    python3-pip \
    strongswan \
    strongswan-pki \
    libcharon-extra-plugins \
    libcharon-extauth-plugins \
    libstrongswan-extra-plugins \
    libtss2-tcti-tabrmd0

RUN apt install -y \
    socat \
    openssh-server \
    sshuttle \
    netcat \
    vim

RUN mv -f /etc/ipsec.conf /etc/ipsec.conf.bak && \
    mv -f /etc/ipsec.secrets /etc/ipsec.secrets.bak && \
    mv -f /etc/sysctl.conf /etc/sysctl.conf.bak

COPY $CONFIG_DIR_SRC/systemctl /usr/bin/systemctl
COPY $CONFIG_DIR_SRC/sysctl.conf /etc/sysctl.conf
COPY $CONFIG_DIR_SRC/ikev2_ipsec.conf /.dockerconfig/ipsec.conf 
COPY $CONFIG_DIR_SRC/ikev2_ipsec.secrets /.dockerconfig/ipsec.secrets
COPY $CONFIG_DIR_SRC/ikev2_iptables_config.sh /.dockerconfig/iptables_config.sh
COPY $CONFIG_DIR_SRC/ikev2_entrypoint.sh /.dockerinit

RUN chmod 755 /usr/bin/systemctl
RUN chmod 644 /etc/sysctl.conf
RUN chmod 644 /.dockerconfig/ipsec.conf
RUN chmod 600 /.dockerconfig/ipsec.secrets
RUN chmod 755 /.dockerconfig/iptables_config.sh
RUN chmod 755 /.dockerinit

CMD "/bin/bash"
ENTRYPOINT ["/.dockerinit"]